### ISSUE TITLE
tintColor of the JGProgressHUDImageIndicatorView

### ISSUE THREAD

**Issue by lchamp** [JonasGessner/JGProgressHUD#100]
Hello,

_This is my first comment, sorry in advance for my english and the formatting._

Within `JGProgressHUDErrorIndicatorView` and `JGProgressHUDSuccessIndicatorView` you have the exact same two methods:
`- (void)setUpForHUDStyle:(JGProgressHUDStyle)style vibrancyEnabled:(BOOL)vibrancyEnabled`
`- (void)tintColorDidChange`

1 - Why aren't the moved within `JGProgressHUDImageIndicatorView` directly?

Imagine I'm using the error hud like so:
```
JGProgressHUD *jgHUD = [JGProgressHUD progressHUDWithStyle:JGProgressHUDStyleDark];
jgHUD.textLabel.text = title;
jgHUD.delegate = self;
jgHUD.indicatorView = [[JGProgressHUDErrorIndicatorView alloc] init];
[jgHUD showInView:self.view animated:false];
[jgHUD dismissAfterDelay:2.0];
```

The image should therefore be white (because the style used is `JGProgressHUDStyleDark`).
However, since there is a the:
```
- (void)tintColorDidChange {
    [super tintColorDidChange];
    self.contentView.tintColor = self.tintColor;
}
```
The image color changes to the one set on the `UIViewController` or `Storyboard` when the HUD appears.

2 - What is the purpose off using `- (void)tintColorDidChange` here? Is this a wanted behavior? Am I using it wrong?

Thanks in advance for your response.

**Comment by lchamp** [comment]
@JonasGessner ? 🙂

**Comment by JonasGessner** [comment]
You do make a point and I think I will change something here to make it simpler. But it's something that needs some thought and I will take a look sometime. Feel free to open a PR with a suggested change.
