### ISSUE TITLE
dismiss withCompletion

### ISSUE THREAD

**Issue by FritzHsiao** [JonasGessner/JGProgressHUD#103]
I'm using swift. I've see ur reply on https://github.com/JonasGessner/JGProgressHUD/issues/48
But I'm still can't find any solution, how can I dismiss hud with completion block. Thanks

**Comment by JonasGessner** [comment]
The API of JGProgressHUD has no dismiss method with a completion block. JGProgressHUD needs no explicit cleanup when it is dismissed, as it removes itself from superview and can then be deallocated. Most likely you don't need a completion block. If you still need to be notified exactly when the HUD has disappeared you can use the delegate methods (https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L304).
