### ISSUE TITLE
about super load 

### ISSUE THREAD

**Issue by gerald8** [JonasGessner/JGProgressHUD#108]
Hi, u don't have to call [super load] from your code. The load method from all superclasses has already been called by the Objective-C runtime before the method in your subclass is called. if you call [super load];, the superclass' implementation will run twice!  This code made my method swizzling invalid.

The first time:
**A(IMP = original)** -> **A(IMP= exchanged)**

The second time:
**A(IMP = exchanged)** -> **A(IMP= original)**

More details [https://stackoverflow.com/questions/34542316/does-method-load-need-to-call-super-load](https://stackoverflow.com/questions/34542316/does-method-load-need-to-call-super-load)

**Comment by kzq5** [comment]
Because the wrong use of this method caused my other code to be invalid, looking for a long time to find.

**Comment by JonasGessner** [comment]
Thanks. Feel free to open a PR with this change.
