### ISSUE TITLE
Not working correctly on UITableView

### ISSUE THREAD

**Issue by usmaak** [JonasGessner/JGProgressHUD#109]
If I use it on a UITableView, the progress view sticks with the center of the top of the list.

To reproduce, add the progress view to a tableview that has a lot of rows.  Scroll up and fire the progress view.  It will be stuck at the top center of the first set of rows.  This results in it not being visible if I've scrolled past all of the first set of rows that were visible when first starting my app.

**Comment by JonasGessner** [comment]
This behavior is expected. A UITableView changes its bounds when it scrolls and it is not in the realm of the hud to assume you don't want this and compensate for the change in bounds. You should not present a hud in a scrollable view, instead present it in your table view's superview, for example.

**Comment by usmaak** [comment]
Thank you.  I am sorry to bother you with something that wasn't an issue.

**Comment by JonasGessner** [comment]
No worries at all.
