### ISSUE TITLE
Progress HUD not covering full screen.

### ISSUE THREAD

**Issue by manvendrasah** [JonasGessner/JGProgressHUD#115]
I am using version 2.0.3.
<img width="324" alt="screenshot_iPhoneXR" src="https://user-images.githubusercontent.com/27662489/57065245-79029100-6ce6-11e9-9cb7-a5c03af6ea2a.png">

I am using the following code snippet in a helper file to show the progress HUD.

        var progressBar = JGProgressHUD(style: .light)
        progressBar?.detailTextLabel.text = "Loading.."
        progressBar?.textLabel.text = "Some message . "
        progressBar?.contentView.backgroundColor = .white
        progressBar?.backgroundColor = getColor(black50)
        progressBar?.show(in: self.view)

I am putting a translucent background behind the progress view.        

As seen in the attached image, the Progress HUD isn't covering the full screen. I have tried changing the Edge Insets and also changing the frame rect. But still the full screen is not getting covered by the translucent background.

What is the solution for this ?

**Comment by JonasGessner** [comment]
You must show the HUD inside a view that fully covers the screen to achieve your desired behavior.  The HUD, or its background, will only cover the area of its superview.
