### ISSUE TITLE
SwiftUI compatibility

### ISSUE THREAD

**Issue by pepperoni505** [JonasGessner/JGProgressHUD#121]
Trying to get this to work in SwiftUI is impossible - I have code that wraps it in a `UIView` that can be displayed in a `View`:
```
import SwiftUI
import UIKit
import JGProgressHUD

struct ProgressHUD: UIViewControllerRepresentable {
    
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<ProgressHUD>) -> ProgressHUD.UIViewControllerType {
        let hud = JGProgressHUD(style: .dark)
        hud.textLabel.text = "Loading"
        hud.dismiss(afterDelay: 3.0)
        
        return hud
    }
    
    
    func updateUIViewController(_ uiViewController: ProgressHUD, context: UIViewControllerRepresentableContext<ProgressHUD>) {
        print("")
    }
}

```
If you could consider adding some basic SwiftUI compatibility that would be very much appreciated.

**Comment by c941010623** [comment]
I have a good idea.
You can try it.

`
//
//  ProgressHUD.swift
//  iGirls
//
//  Created by Shih-Chan Lin on 2020/2/17.
//  Copyright © 2020 Shih-Chan Lin. All rights reserved.
//

import SwiftUI
import JGProgressHUD

class ProgressHUDController: UIViewController {
    let hud = JGProgressHUD(style: .dark)
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.dismiss()
    }
    
    func show(text: String) {
        hud.textLabel.text = text
        hud.show(in: self.view)
    }
    
    func dismiss() {
        print("dismiss ~~~")
        hud.dismiss()
    }
}

struct ProgressHUD: UIViewControllerRepresentable {
    func makeUIViewController(context: UIViewControllerRepresentableContext<ProgressHUD>) -> ProgressHUDController {
        ProgressHUDController()
    }
    
    func updateUIViewController(_ uiViewController: ProgressHUDController, context: UIViewControllerRepresentableContext<ProgressHUD>) {
        uiViewController.show(text: "Loading ...")
    }
    
    typealias UIViewControllerType = ProgressHUDController
}

public struct ProgressHUDView<Content>: View where Content: View {
    private var isShowing: Binding<Bool>
    private var content: () -> Content
    
    public init(isShowing: Binding<Bool>, content: @escaping () -> Content) {
        self.isShowing = isShowing
        self.content = content
    }
    
    public var body: some View {
        ZStack(alignment: .center) {
            if (!self.isShowing.wrappedValue) {
                self.content()
            } else {
                self.content()
                    .disabled(true)
                    .blur(radius: 3)
                
                ProgressHUD()
            }
        }
    }
}

struct ProgressView: View {
    @State var isShow: Bool = false
    
    var body: some View {
        ProgressHUDView(isShowing: self.$isShow) {
            Button(action: {
                self.isShow.toggle()
                DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(2000)) {
                    self.isShow.toggle()
                }
            }) {
                Text("Try Me!")
            }
        }
    }
}

struct ProgressView_Previews: PreviewProvider {
    static var previews: some View {
        ProgressView()
    }
}

`

**Comment by c941010623** [comment]
I have a good idea.
You can try it.

```
test
```

**Comment by anushkmittal** [comment]
@pepperoni505 did the above example work for you?

**Comment by RuslanIskhakov** [comment]
Hi everybody
The following SwiftUI wrapper works for me

`import UIKit
import SwiftUI

struct SwiftUIProgressHUDView: View {
    
    var body: some View {
        GeometryReader {geometry in
            ProgressHudViewWrapper()
                .frame(width: geometry.size.height, height: geometry.size.height)
        }
    }
}

private struct ProgressHudViewWrapper: UIViewRepresentable {
    func makeUIView(context: Context) -> BridgeProgressHUDView {
        return BridgeProgressHUDView(frame: CGRect())
    }

    func updateUIView(_ uiView: BridgeProgressHUDView, context: Context) {
    }
}

private class BridgeProgressHUDView: UIView, ProgressHUD {
    
    var progress: ProgressHUDClass? = nil
    var view: UIView!
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.view = self
        self.showProgress()
    }
    override init(frame: CGRect) {
        super.init(frame: frame)
        self.view = self
        self.showProgress()
    }
}

#if DEBUG
struct SwiftUIProgressHUDView_Previews: PreviewProvider {
    static var previews: some View {
        return SwiftUIProgressHUDView()
    }
}
#endif`

**Comment by pepperoni505** [comment]
@anushkmittal Sorry, I took a break from developing for a bit. I forgot I had this open so I closed this.

**Comment by JonasGessner** [comment]
I made a compatibility layer for SwiftUI, it's available here: https://github.com/JonasGessner/JGProgressHUD-SwiftUI
