### ISSUE TITLE
support Dark mode !

### ISSUE THREAD

**Issue by X901** [JonasGessner/JGProgressHUD#122]
Could you support dark by default

if the user turn Dark mode off the style be light
but when turn Dark mode on the style change to dark

**Comment by JonasGessner** [comment]
I see a few problems here:  Would the non dark mode color be light or extra light? What happens on old OSes that don't have dark mode? Also the style is currently a readonly property and there is no tested mechanism that supports changing the style in arbitrary moments.

A pretty powerful API would be adding an optional property (maybe a block or a protocol) which is called whenever the user interface style changes. This block/object can then not only change the hud style but also do any other necessary changes to the HUD. This property can also simply be ignored on an older OS. But the hud style needs to become a writable property.

**Comment by X901** [comment]
for NOW I did it like this

Create new function to check if user in Dark mode or not

```
 static func checkIfUserInDarkMode() ->  JGProgressHUD {
        
        if #available(iOS 13.0, *) {
            if UITraitCollection.current.userInterfaceStyle == .dark {
                print("Dark mode")
                return  JGProgressHUD(style: .dark)
            }
            else {
                print("Light mode")
              return  JGProgressHUD(style: .extraLight)
            }
        }else{
           return JGProgressHUD(style: .extraLight)
        }

    }
```

then on any viewController I use it 

`    let progresshud = ProgressView.checkIfUserInDarkMode()
`

it working fine

**Comment by thejeff77** [comment]
Ha. Just wrote almost the exact same code and posted it in another issue. 

https://github.com/JonasGessner/JGProgressHUD/issues/129

Good times.

**Comment by mman** [comment]
I think for now the easiest thing would be to add ``.automatic`` ``JGProgressHUDStyle`` that will determine whether to use ``.dark`` or ``.light`` style when the HUD is shown based on view's user interface style.

Second step would be to listen in the shown HUD for ``traitsCollectionDidChange`` and change look appropriately.

**Comment by JonasGessner** [comment]
I added a mode that automatically changes the HUD style based on the UITraitCollection interface style. It's on master at the moment and will eventually go into stable and be part of a new release. At that point checking out this repo with SPM/CocoaPods/Carthage will include the changes. Feel free to try out this feature by pulling from the master branch. I'm leaving this issue open until this feature is on stable.
