### ISSUE TITLE
Xcode 10 Carthage compile error

### ISSUE THREAD

**Issue by gilroykilroy** [JonasGessner/JGProgressHUD#124]
JGProgressHUDIndeterminateIndicatorView.m:17:97: error: use of undeclared identifier 'UIActivityIndicatorViewStyleLarge'
        activityIndicatorView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleLarge];

Please make sure all iOS 13 specific calls/variables/constants are in available(iOS 13, *) tests.

**Comment by JonasGessner** [comment]
I updated the tag for v2.1. It should work now if you do a clean install with Carthage.
