### ISSUE TITLE
SPM Cannot call value of non-function type 'module<JGProgressHUD>'

### ISSUE THREAD

**Issue by bhlvoong** [JonasGessner/JGProgressHUD#126]
Currently using Xcode 11.1 and 11.2 BETA with the new SPM dependency feature within the IDE.  Installing my own library of LBTATools works fine through SPM. However, trying to create a hud will flag this error:

let hud = JGProgressHUD(style: .dark)
(Cannot call value of non-function type 'module<JGProgressHUD>')

**Comment by JonasGessner** [comment]
Make sure you're using version 2.1 where SPM works correctly. Version 2.0.4 only supports Accio (which requires a Package.swift file) but not SPM.

**Comment by bhlvoong** [comment]
In the Xcode SPM dependency menu, it seems to only allow versions of x.y.z so it's not resolving 2.1 for me.  That said, using the "master" options allows me import and create huds successfully.

**Comment by JonasGessner** [comment]
Well that's inconvenient.. I pushed a tag `2.1.0` where it works.
