### ISSUE TITLE
Add completion callback to dismiss()

### ISSUE THREAD

**Issue by lechuckcaptain** [JonasGessner/JGProgressHUD#127]
Please add a completion callback to dismiss functions, in order to avoid strange behaviour during dismissal animation.

**Comment by JonasGessner** [comment]
Could you give a specific case where this would be useful? The HUD removes itself from superview automatically when it is dismissed and can then be released without having to do anything manually, except removing strong references to it.

**Comment by lechuckcaptain** [comment]
The case is the following, I want to navigate in another ViewController (e.g. popToViewController) after the HUD is dismissed, without needing to know the exact duration of the animation of the dismiss of the HUD. With a completion callback I can get this functionality for free. Let me know if it's clear of you need a working example.

**Comment by lechuckcaptain** [comment]
@JonasGessner my explanation was enough clear or do you need a working example?

**Comment by JonasGessner** [comment]
I will most likely add this to the project. I am pretty busy at the moment though. Feel free to open a PR.

**Comment by jbmaxwell** [comment]
> Could you give a specific case where this would be useful? The HUD removes itself from superview automatically when it is dismissed and can then be released without having to do anything manually, except removing strong references to it.

Actually, in my experience, it doesn't remove itself. Or if it does remove itself, it doesn't also dismiss itself, so it lingers around on my screen ad infinitum... and I can't dismiss it, because I've defined it as an force-unwrapped Optional, and if I call `.dismiss()` it crashes my app.

**Comment by StormKop** [comment]
@JonasGessner seems like there is already a pull request for this. Hopefully the PR can be closed :)

**Comment by JonasGessner** [comment]
An implementation of this is now on master. It does not have a release yet, so it is still not usable on package managers like SPM. But you can pull the master branch and try it out.
