### ISSUE TITLE
App crash when i call the background method

### ISSUE THREAD

**Issue by nileshordex** [JonasGessner/JGProgressHUD#134]
I am using pusher and call the method the app crash on the JGProgressHUD.m and line no 476

line no 476 : [NSLayoutConstraint constraintWithItem:self attribute:NSLayoutAttributeCenterX relatedBy:NSLayoutRelationEqual toItem:_targetView attribute:NSLayoutAttributeCenterX multiplier:1.0 constant:0.0].active = YES;

Please give solution for this crash point.

**Comment by JonasGessner** [comment]
Please upload details on the crash: logs, OS version, etc.

**Comment by nileshordex** [comment]
I have found the issue and fixed it.

Thank you so much for the replay to me.

**Comment by nileshordex** [comment]
The issue is when I call the method and show the progress HUD display on self.view so I change self.view to 
myAppDeletegate.navController.topViewController.view and solved the issue.

Again Thank you very much.
