### ISSUE TITLE
Feature Request: showAfterDelay

### ISSUE THREAD

**Issue by mman** [JonasGessner/JGProgressHUD#136]
Hi @JonasGessner, thanks for this great little library. I often use indeterminate progress indicators in a way to automatically pop up onscreen after certain delay, when a networking operation takes too long to complete. I often need to show them after one second, and then dismiss when operation completes. I use ``DispatchWorkItem`` to schedule ``[hud show]`` after delay on ``DispatchQueue.main``.

Would be cool if the hud itself can be ``[hud showAfterDelay: 1]`` tracking the ``DispatchWorkItem`` internally and canceling it when ``[hud dismiss]`` is invoked.

Would you be interested for me to open a PR?

**Comment by JonasGessner** [comment]
Hey, sure! Sounds like you have a good design in mind for this, so feel free to go ahead with a PR.

**Comment by JonasGessner** [comment]
I'm not planning to implement this feature. If you want to create a PR, feel free. Otherwise I will close this issue.

**Comment by mman** [comment]
@JonasGessner Thanks for kicking me into doing it. It's in the https://github.com/JonasGessner/JGProgressHUD/pull/145. Hope I have not missed anything.

**Comment by JonasGessner** [comment]
Closed via #145
