### ISSUE TITLE
Incorporate NVActivityIndicatorView Animations

### ISSUE THREAD

**Issue by thejeff77** [JonasGessner/JGProgressHUD#137]
Hey there! 

This library is great. I was checking out the ability to subclass and add your own animations. It would be awesome to have a base of included animations for this project and NVActivityIndicatorView came to mind. https://github.com/ninjaprox/NVActivityIndicatorView

JGProgressHUD is easier to use, looks better and has more options, so I'd definitely not want to switch away from it. 

Would it be straightforward to add in animation support for the open source animations provided by NVActivtyIndicatorView? It is a fantasic base of animations that would work for almost anything, under the MIT License.

**Comment by JonasGessner** [comment]
Hey, this looks like a great extension to JGProgressHUD. I definitely want to avoid shipping with a dependency by default. But you could easily create a custom `JGProgressViewIndicatorView` that wraps `NVActivityIndicatorView` and make it a separate library that can be used as extension (meaning make it a separate SwiftPM/cocoapod/carthage). That way one can use the standard JGProgressHUD library, and optionally add the separate NVActivityIndicatorView extension.

**Comment by thejeff77** [comment]
Thanks Jonas, that's a great idea.

I'd actually love to take this on. Since I'm pretty new to animations and haven't learned either codebase very well - it would likely take me more time than I'd be enthusiastic to spend on such an extension. However if you think you might be familiar enough with this sort of thing to get a quick gist in an hour or less for adding one animation, I'd be able to make quick work of such an extension library. Even something that hard-codes even one of the animation class - https://github.com/ninjaprox/NVActivityIndicatorView/tree/master/Source/NVActivityIndicatorView/Animations - into JGProgressHUD would really help, as I could abstract patterns from there.

If not no worries, it's worth asking! I'm trying to solicit help/guidance for anything outside my wheelhouse for open source contributions to keep any contributions rolling at a good pace.

**Comment by JonasGessner** [comment]
I unfortunately can't help you with the implementation. There are a number of examples of `JGProgressViewIndicatorView` subclasses, such as `JGProgressHUDImageIndicatorView` or  `JGProgressHUDPieIndicatorView`. Taking these as a reference it should be fairly straightforward. I'm also not familiar with `NVActivityIndicatorView` at all. I'm closing this issue because it is not directly related to the main library, but please feel free to continue working on this extension.
