### ISSUE TITLE
Size of JGProgressHUDIndicatorView

### ISSUE THREAD

**Issue by IronMaltes** [JonasGessner/JGProgressHUD#139]
Hi Jonas, first of all thanks for you work, it's a nice library.

I would like to know if there's any restriction on the size of the view of the JGProgressHUDIndicatorView.

I'm playing with that and I find that I can create something like you see in the image attached but the buttons that are not at the center can not be clicked (I'm guessing that because I had to setup the CGFrame to -30 to get that effect you see...)

Thanks!

<img width="197" alt="Captura de pantalla 2020-06-01 a las 23 26 53" src="https://user-images.githubusercontent.com/32038447/83456160-74fff000-a45f-11ea-9886-47cf27ac532a.png">

**Comment by IronMaltes** [comment]
Jonas, I just solved the problem modifying the size of the superview of the JGProgressHUDIndicatorView. So problem fixed.

Thanks anyway!

**Comment by JonasGessner** [comment]
Hey, your view needs to have its intrinsic content size set properly in order for this to work. If you are using autolayout it should be set automatically if you have proper constraints set for your indicator view (i.e something like the indicator view must be at least the size of the 5 stars). If you are not using autolayout you need to manually set the intrinsic content size
