### ISSUE TITLE
Better animations

### ISSUE THREAD

**Issue by xzenon** [JonasGessner/JGProgressHUD#14]
Sorry for bothering you again.
Current HUD transition between states without text and with some text/details (and when changing visible text/details values) does not really look good - 
text/detail labels are floating over the HUD borders. Is it possible to somehow fix these transitions (to make text labels appearing from the center of HUD and not crossing the HUD borders)?
Here is the example video: http://youtu.be/IVEkKvK_wRs
Thanks.

**Comment by JonasGessner** [comment]
Closed due to inactivity.
