### ISSUE TITLE
Don't show up immediately

### ISSUE THREAD

**Issue by karleenchoie** [JonasGessner/JGProgressHUD#140]
I have problem regarding the first set-up of loading doesn't show up immediately and then after few seconds, the loading will appear. please help me thanks

**Comment by JonasGessner** [comment]
This sounds very much like an unrelated issue, such as: You're calling from a background thread, or you are blocking the calling thread. If you are sure this is a bug in JGProgressHUD please provide a MWE and reopen the issue.
