### ISSUE TITLE
How to achieve Multiple Spinners showing at same time by using this library?

### ISSUE THREAD

**Issue by GaneshMyNewCar** [JonasGessner/JGProgressHUD#142]
Thanks for the simple & effective repository. 
How to show multiple Spinners at a time asynchronously. I'm trying to achieve with GCD, but not working.
Does anyone know about this?

**Comment by JonasGessner** [comment]
You can instantiate `JGProgressHUD` as often as you want. Each instance is completely independent. If you want to show two HUDs simultaneously, you just need to create two different instances and show them in two different views.
