### ISSUE TITLE
Add a blur view BEHIND the hud

### ISSUE THREAD

**Issue by rob8861** [JonasGessner/JGProgressHUD#144]
From the documentation: 
- To dim the content behind the HUD set your dim color as backgroundColor of your JGProgressHUD instance.

my question is: instead of dimming, is there a way to make the background view a blur view?

**Comment by JonasGessner** [comment]
This is not possible out of the box, but can easily be done manually using a `UIVisualEffectView`. Basically you could add a `UIVisualEffectView` on top of the view you are showing the HUD on, then show the HUD on the `UIVisualEffectView`. I don't have plans of making this a default feature though.
