### ISSUE TITLE
Unable to resolve SPM dependency in Xcode

### ISSUE THREAD

**Issue by SeanAsby** [JonasGessner/JGProgressHUD#146]
All of a sudden Xcode is not able to resolve JGProgressHUD as an SPM dependency. Did something recently change that may have caused this?

**Comment by SeanAsby** [comment]
Seems to be back up 🤷

**Comment by JonasGessner** [comment]
Yes, I accidentally deleted a tag. Sorry!

**Comment by SeanAsby** [comment]
No problem. Was just wondering 😊
