### ISSUE TITLE
JGProgressHUD(automaticStyle: ()) doing the opposite

### ISSUE THREAD

**Issue by nitishrana28** [JonasGessner/JGProgressHUD#148]
I am initialising like this to get advantage of adjustment to theme (light/dark) 
`let progressView = JGProgressHUD(automaticStyle: ())`

But it does the opposite. For light theme, the hud is of light background and for dark, it is of black.
It should be the other way around.

**Comment by JonasGessner** [comment]
`It should be the other way around.`

**Comment by JonasGessner** [comment]
> It should be the other way around.
According to whom?

**Comment by nitishrana28** [comment]
Go through my second part of question. The way you have implemented it, it shows in light background in light theme and black bavkground in dark theme. That way we are not able to see the background clearly. 
In light mode, the background should be black and in dark mode background should be light. For visibility. This should atleast be the default setup.

**Comment by JonasGessner** [comment]
I totally understand your point about visibility. But I disagree with you saying there is a right and a wrong way. It depends on whether you want to have contrasting color. Apple's native HUDs use the same color choice as JGProgressHUD as an example (eg in the Music app).

I have been thinking about a flexible way of allowing to customize the light and dark mode appearance (beyond just HUD style) and may add some sort of customization feature in the future. For now the default automatic styling will stay as it is though.
