### ISSUE TITLE
How to change shadow

### ISSUE THREAD

**Issue by xuzhanqian** [JonasGessner/JGProgressHUD#150]
I want to change to this style, but I can't find the corresponding property.
<img width="101" alt="截屏2021-03-01 上午9 26 27" src="https://user-images.githubusercontent.com/10412209/109441450-3fc91280-7a70-11eb-8cad-a7868072c340.png">

**Comment by JonasGessner** [comment]
You set the shadow via the `shadow` property and its of the type `JGProgressHUDShadow`. https://jonasgessner.github.io/JGProgressHUD/Classes/JGProgressHUD.html#//api/name/shadow
