### ISSUE TITLE
Cannot recreate the demo style

### ISSUE THREAD

**Issue by stateman92** [JonasGessner/JGProgressHUD#152]
I would like to recreate exactly this type of animation: [gif from the repository](https://raw.githubusercontent.com/JonasGessner/JGProgressHUD/master/Examples/Screenshots/demo1.gif). I tried out the example project, and I analized the library (as far as I can, since my main language is swift), but in every case the label (which has a text "Loading" on the upper gif) has a white or black text color. I tracked back this problem to this line: [the given codeline](https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.m#L815). Can we achieve the style on the upper gif with this library? If yes, then how? Any code snippet or advice is highly appreciated, even in Objective-C, I can transform it.

(The main part of the desired style is that it should has a label which is masked out of the blur view, and the label should show the background of the hud.)

**Comment by JonasGessner** [comment]
You need to enable the `vibrancyEnabled` flag to get that style. The code used to create the demo gif is here: https://github.com/JonasGessner/JGProgressHUD/blob/master/Examples/JGProgressHUD-Tests-Swift/ViewController.swift#L89

**Comment by stateman92** [comment]
Thank you very much, it works!
