### ISSUE TITLE
Ios 16 dynamic island 

### ISSUE THREAD

**Issue by furiosFast** [JonasGessner/JGProgressHUD#154]
Hi,
is possible to use the dynamic island on ios 16 to show the progress hud?

**Comment by sabiland** [comment]
That would be cool!

**Comment by JonasGessner** [comment]
That falls outside of the scope of this kind of UI element. It would be better suited to create a dedicated UI element that is tailored at the dynamic island (for which I don't have any plans).

Also, AFAIK it is also not recommended by Apple to design anything to specifically follow the shape of the dynamic island. Many iOS devices don't have a dynamic island, the shape may change in the future, etc.
