### ISSUE TITLE
Fatal Exception : NSINternalInconsistencyException (HUD is currently transitioning)

### ISSUE THREAD

**Issue by TheGManC** [JonasGessner/JGProgressHUD#17]
Hi,

Great library. however, I get this crash every now and again: Fatal Exception : NSINternalInconsistencyException (HUD is currently transitioning)

The culprit line is JGProgressHUD.m line 384 - [JGProgressHUD showInRect:inView:animated:]

**Comment by JonasGessner** [comment]
Fixed in 4f007cde2033da26ec5ad31e1866c887aa91368a.
