### ISSUE TITLE
Used with Swift?

### ISSUE THREAD

**Issue by grafikerkam** [JonasGessner/JGProgressHUD#22]
hello, is add to swift project? Thank you.

**Comment by JonasGessner** [comment]
I will possibly migrate the project to swift in the future (while maintaining the original objc code for sure). You can however use JGProgressHUD in a swift project by using a Bridging header. There's even a guide for this: http://swiftalicio.us/2014/11/using-cocoapods-from-swift/

**Comment by grafikerkam** [comment]
thank u.
