### ISSUE TITLE
Add GracePeriod Option

### ISSUE THREAD

**Issue by benmarten** [JonasGessner/JGProgressHUD#23]
I would like to see an option for setting a grace period. I have subclassed JGProgressHUD for one of my projects. Maybe you want to implement something similar?

#import "JGProgressHUD.h"

@interface FSProgressHUD : JGProgressHUD

@property NSNumber* graceTime;
@property BOOL taskInProgress;
@property BOOL showInSuperview;

- (void)showInView:(UIView*)view;
- (void)dismiss;

@end

#import "FSProgressHUD.h"

@interface FSProgressHUD ()

@property NSTimer* graceTimer;
@property UIView* view;

@end

@implementation FSProgressHUD

/**
 Shows the HUD animated. You should preferably show the HUD in a UIViewController's view.
 @param view The view to show the HUD in. The frame of the @c view will be used to calculate the position of the HUD.
 */
- (void)showInView:(UIView*)view
{
    if (_graceTime && [_graceTime doubleValue] > 0.0) {
        _view = view;
        _taskInProgress = YES;
        _graceTimer = [NSTimer scheduledTimerWithTimeInterval:[_graceTime doubleValue] target:self
                                                     selector:@selector(handleGraceTimer:)
                                                     userInfo:nil
                                                      repeats:NO];
    }
    else {
        [super showInView:view];
    }
}

- (void)dismiss
{
    _taskInProgress = NO;
    [super dismiss];
}

- (void)handleGraceTimer:(NSTimer*)theTimer
{
    if (_taskInProgress) {
        if (_showInSuperview && _view.superview) {
            [super showInView:_view.superview];
        }
        else {
            [super showInView:_view];
        }
    }
}

@end

**Comment by JonasGessner** [comment]
This is unnecessary, a simple `dispatch_after` call can take care of this.
