### ISSUE TITLE
Blurry font

### ISSUE THREAD

**Issue by mylittlehero** [JonasGessner/JGProgressHUD#27]
Hi Jonas

The font in the progress hud seems a bit blurry..

I already changed the font and frame size, but something seems to be wrong.

Thanks

**Comment by JonasGessner** [comment]
The background is blurred, the label isn't. The background might give the illusion that the text is blurred as well :P

**Comment by mylittlehero** [comment]
No.

I'm using the progress HUD after a database request. As soon as I got the results, a UIAlertView appears. After a small comparison between the texts I noticed the blur in the HUD text.

Check it by yourself. Maybe you got that good eyes as well ;). It's already fixed in my code.

**Comment by JonasGessner** [comment]
I don't know what the technical explanation should be if there really is any blur. Could you post some screenshots?

**Comment by mylittlehero** [comment]
Just compare the text of an UIAlertView and your progress HUD (for example "Loading..) font size 17.0. I fixed it by using "CGRectIntegral".

**Comment by JonasGessner** [comment]
You're right.. You have some damn good eyes! :P I'll push an update in the coming weeks to fix this. Respect for noticing!

**Comment by mythodeia** [comment]
@mylittlehero where did you made the change to ```CGRectIntegral```

**Comment by mylittlehero** [comment]
@mythodeia In JGProgressHUD.m after line 226 add: ```labelFrame = CGRectIntegral(labelFrame);```

**Comment by mythodeia** [comment]
@mylittlehero thanks :+1:
