### ISSUE TITLE
Any plans of making it a dynamic library?

### ISSUE THREAD

**Issue by danqing** [JonasGessner/JGProgressHUD#28]
As iOS 8 supports dynamic libraries, it will be great if there can be a dynamic version of this library. Then it can be installed using Carthage for example, and I think that's more friendly than a static library.

**Comment by JonasGessner** [comment]
A framework or dylib? Carthage uses frameworks AFAIK.

**Comment by danqing** [comment]
Yes framework =)

**Comment by JonasGessner** [comment]
I added a framework target in 3bf02f3dcaebf9628b02b2e72766f6de8d17c044. Cheers.

**Comment by danqing** [comment]
Thanks Jonas!
