### ISSUE TITLE
Rotation Issue

### ISSUE THREAD

**Issue by mylittlehero** [JonasGessner/JGProgressHUD#29]
Hi Jonas

Found another issue.

I've got a "portrait-only" ViewController, which is called from a normal (portrait and landscape) ViewController. Now when I am in landscape mode and go to the portrait-only ViewController, the ProgressHUD is displayed quite wrong.. This issue also appears while changing orientation.

Thanks for your great code anyway. It's a very cool HUD :)

**Comment by JonasGessner** [comment]
Any example code/project and screenshots would be useful.

**Comment by mylittlehero** [comment]
No code needed. Just create a portrait-only mode and use your HUD. As soon the orientation changes while the HUD is in front, you'll see it.

**Comment by JonasGessner** [comment]
Show me your code. If you want to help thats the least you can do. Or just fix it yourself open a pull request.

**Comment by gulullu** [comment]
Hi Jonas
I found this issue too. 
My code is almost same with this: http://swiftiostutorials.com/ios-orientations-landscape-orientation-one-view-controller/
The ProgressHUD is displayed quite wrong on the only one landscape  view controller.

**Comment by JonasGessner** [comment]
I'm really busy right now and I don't have the time to look into this. Everyone is welcome to contribute, that's why this project is open source. You can fork the repo, fix any bugs you find and open a pull request.

**Comment by JonasGessner** [comment]
I will close this ticket if it is no longer updated. If you want this to be fixed you have to show me some code instead of trying to vaguely explain your implementation.

**Comment by JonasGessner** [comment]
You're free to reopen this and provide more information.
