### ISSUE TITLE
Add new feature

### ISSUE THREAD

**Issue by lltu** [JonasGessner/JGProgressHUD#32]
I like this code!
But ,  I want to run some code after progressHUD dismissed, Could add some block after JGProgressHUD dismissed ?
I think this feature is very useful !
Thank you.

**Comment by JonasGessner** [comment]
It seems like you haven't even looked at the code https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L53
