### ISSUE TITLE
Support adding UIImageView as a subview to `.contentView`

### ISSUE THREAD

**Issue by sindresorhus** [JonasGessner/JGProgressHUD#34]
It seems to loose the padding when I do so.

```objective-c
JGProgressHUD *HUD = [JGProgressHUD progressHUDWithStyle:JGProgressHUDStyleLight];
HUD.indicatorView = nil;
[HUD.contentView addSubview:[[UIImageView alloc] initWithImage:[UIImage imageNamed:@"hud-saved"]]];
[HUD showInView:self.view];
```

Results in:

![](https://cloud.githubusercontent.com/assets/170270/8019522/34ab4724-0c53-11e5-9ca8-cfbeb7093b8e.png)

-

Weirdly enough this works, though with a warning:

```objective-c
JGProgressHUD *HUD = [JGProgressHUD progressHUDWithStyle:JGProgressHUDStyleLight];
HUD.indicatorView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"hud-saved"]];
[HUD showInView:self.view];
```

![](https://cloud.githubusercontent.com/assets/170270/8019528/929716a6-0c53-11e5-8dff-f4f4341da18c.png)

**Comment by JonasGessner** [comment]
http://a9-19.1-409.cdn13.com/004/401/4401454.flv?cdn_creation_time=1433623338&cdn_ttl=14400&cdn_bw=153600&cdn_bw_fs=3m&cdn_hash=f1057c2b0a1e4fad9f5095e21468f97b

**Comment by JonasGessner** [comment]
https://github.com/JonasGessner/JGProgressHUD#indicator-views

**Comment by JonasGessner** [comment]
You need to create a custom indicator view. Obviously your last piece of code results in a warning because you are assigning a UIImageView to a property of `JGProgressHUDIndicatorView`. You can look at the error and success indicator views and pretty much use the same implementation.

**Comment by sindresorhus** [comment]
I noticed, but I only need to show an image there, so sub-classing feels overly bloated. You already have a `textLabel` option, so would you be willing to have a `indicatorImage` option to make the common case easy?

With `MBProgressHUD` I could do the following which was much nicer:

```objective-c
MBProgressHUD *HUD = [[MBProgressHUD alloc] initWithView:self.view];
[self.view addSubview:HUD];
HUD.mode = MBProgressHUDModeCustomView;
HUD.delegate = self;
HUD.customView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"hud-saved"]];
```

*Notice the `HUD.customView`*

**Comment by JonasGessner** [comment]
Yeah thats a good idea. The next release will feature a standard `JGProgressHUDImageIndicatorView` (from which the error and success indicators will inherit). Cheers!

**Comment by sindresorhus** [comment]
Thank you. Just tried it, works perfectly.

I'm using this in my app [Blear](http://sindresorhus.com/blear/).

**Comment by JonasGessner** [comment]
Sweet!
