### ISSUE TITLE
iOS9

### ISSUE THREAD

**Issue by flavionegrao** [JonasGessner/JGProgressHUD#39]
Hi Jonas, any plans for iOS9?
![img_2408](https://cloud.githubusercontent.com/assets/1597236/10074663/a47769fc-62a7-11e5-9c1d-785e2b04c72f.PNG)

Cheers, Flavio

**Comment by JonasGessner** [comment]
I'm not sure what the question is, I'm guessing the missing contrast, you can add a drop shadow to the HUD or dim the background.

**Comment by flavionegrao** [comment]
Sorry for that, my fault, I thought I had seen something wrong with the image.
Thanks mate and sorry for bothering u.
