### ISSUE TITLE
Not centered

### ISSUE THREAD

**Issue by emaddoma** [JonasGessner/JGProgressHUD#40]
![See](http://i.imgur.com/MAqEFgx.png)

```
import UIKit

class MyViewController: UIViewController {
    
    var hud : JGProgressHUD!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        hud = JGProgressHUD(style: JGProgressHUDStyle.Light)
        hud.showInView(self.view)
    }
    
}

```

**Comment by JonasGessner** [comment]
Could you provide more code? Are you presenting the view controller in a navigation view controller? I need more context.

**Comment by emaddoma** [comment]
The root view controller is a UINavigationController.  The view presenting the HUD is just a view controller presented by the nav controller.  I'm using autolayout and everything else is positioned as expected.

**Comment by JonasGessner** [comment]
Try presenting the hud in viewDidAppear, that might be it. It could also be auto layout doing evil things, which isn't a rarity.

**Comment by emaddoma** [comment]
That worked!  Thanks
