### ISSUE TITLE
important problem

### ISSUE THREAD

**Issue by qiudengqiang** [JonasGessner/JGProgressHUD#43]
How to make a progress bar when the progress bar shows that it can be operation interface, because when a progress bar pops up, now he can only wait for, and can't do any operation, thank you

**Comment by JonasGessner** [comment]
Doesn't really seem like an "important problem" to me. And I don't get what you're trying to do. You should check the <a href="Examples">Examples</a> project, it contains multiple implementations of determinate and indeterminate progress.

**Comment by qiudengqiang** [comment]
Thank you for your reply, I have a look at it
