### ISSUE TITLE
HUD position issue

### ISSUE THREAD

**Issue by Austinate** [JonasGessner/JGProgressHUD#44]
Hi, first of all — thanks for awesome lib that you've made!

Unfortunately, i've faced an issue with it :( 

Version: 1.3.1
iOS versions: 8&9. Both simulator & device. 

Flow: 
1. present HUD in UIViewControllers view
2. push another view controller to navigation stack 
3. rotate device 
4. go back to previous controller 
5. observe wrong position for HUD 

I've made small project which shows the issue: https://github.com/Austinate/JGProgressHudIssue 
You can run UI test testRotation and see what's happening. Sorry if test is bad or it's code smells, it was my first experience with XCTest UI testing :sob: 

[Image](http://i.imgur.com/WUr6AR0.png) that shows issue. 

As i see what's happening — view controllers view bounds doesn't change on rotation if controller wasn't presented on screen during rotation. 

I'm not sure if it's actually any implementation issue for JGProgressHUD (since it's accessing view bound as supposed to do), but i'd like to receive any advice that can help me, thanks! 

### Update 

I was able to fix issue described in ticket, but than i've found that in my case that it still wasn't working so good. What i have: https://imgflip.com/gif/tew5o (gif) 

I've updated test project with proper code to reproduce my issue. What happens: i show spinner in viewWillAppear and hide it after some networking stuff is done. So while appearing animation of HUD is in progress — frame change isn't happening because of this code: 
```
if (_transitioning) {
        _updateAfterAppear = YES;
        return;
    }
``` 

So here comes question: will there be any UI issues if we'd let it to change frame during appear or there was some another reason why this code was added?

**Comment by JonasGessner** [comment]
Hey, thanks for the detailed bug report! I'll look into it soon.

**Comment by Austinate** [comment]
i've made small update on issue and created this pull request to fix case that i had before what i described in update

**Comment by JonasGessner** [comment]
I just wanted to check out your example, but the repo seems to be gone. #47 might fix this issue (I'm merging that PR now).

**Comment by JonasGessner** [comment]
Can you confirm that the issue has been resolved? Otherwise I'll close the ticket due to inactivity.

**Comment by Austinate** [comment]
Hi, sorry for delay, i'll try to check if it's fixed during a couple of days.
