### ISSUE TITLE
dismissAnimated withCompletion

### ISSUE THREAD

**Issue by mommyme** [JonasGessner/JGProgressHUD#48]
Is there a way to dismiss the hud with a completion block? I need to dismiss the hud (animated) on a modal controller, and once the hud is completely dismissed, I need to dismiss the modal controller. Right now, when I try to dismiss the hud and then the modal controller without this method, I get the error: "HUD is not visible" because the modal gets dismissed before the hud gets dismissed.

**Comment by JonasGessner** [comment]
You're using an outdated version of JGProgressHUD. The error message "HUD is not visible" is no longer present in the latest version. You should check out the delegate callbacks, they contain everything you need, specifically this: https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L50
