### ISSUE TITLE
interactionType Unexpected results

### ISSUE THREAD

**Issue by nhart12** [JonasGessner/JGProgressHUD#49]
It seems that the interactionType handling should be reversed. I would assume BlockNoTouches would mean that no touches would be blocked, but in this case, every touch is blocked as seen by the hittest code. 

    if (self.interactionType == JGProgressHUDInteractionTypeBlockNoTouches) {
        return nil;
    }
    else {
        UIView *view = [super hitTest:point withEvent:event];
        
        if (self.interactionType == JGProgressHUDInteractionTypeBlockAllTouches) {
            return view;
        }
        else if (self.interactionType == JGProgressHUDInteractionTypeBlockTouchesOnHUDView && view != self) {
            return view;
        }
        
        return nil;
    }

**Comment by JonasGessner** [comment]
It's the `hitTest` method of the HUD though. So if all touches should be blocked, the HUD captures the touch and nothing is passed to the views behind. If touches should be let through, the `hitTest` method returns `nil`, passing on the touch to the views below it.

**Comment by nhart12** [comment]
ahh yes I knew that too. I just discovered my issue is that I'm showing the hud in a child container view, so it isn't blocking the touches in the parent
