### ISSUE TITLE
JGProgressHUDStyle.Light flickers in iOS 9.3

### ISSUE THREAD

**Issue by rajohns08** [JonasGessner/JGProgressHUD#50]
The frame of the animated circular loading indicator flickers for this style on iOS 9.3

![screen shot 2016-03-24 at 12 08 22 am](https://cloud.githubusercontent.com/assets/2711642/14008933/b307d132-f154-11e5-9f1f-c10046910e9a.png)

**Comment by hemang-azilen** [comment]
@rajohns08, have you ever find any workaround for this? Also, are you able to clear the background color of HUD?

**Comment by rajohns08** [comment]
No, I ended up just using `JGProgressHUDStyle.Dark`

**Comment by dougamos** [comment]
<img width="183" alt="screen shot 2016-04-22 at 16 52 15" src="https://cloud.githubusercontent.com/assets/1301464/14747350/a2e9ceea-08ab-11e6-9b24-9443cb3da0e3.png">
<img width="144" alt="screen shot 2016-04-22 at 16 59 14" src="https://cloud.githubusercontent.com/assets/1301464/14747357/a6fdab0a-08ab-11e6-9bd0-4add48b894b8.png">

The same flickering occurs with .ExtraLight and .Dark only it's less obvious.
