### ISSUE TITLE
Change the HUD background color to clear

### ISSUE THREAD

**Issue by expkzb** [JonasGessner/JGProgressHUD#52]
Now we have three styles JGProgressHUDStyleExtraLight, JGProgressHUDStyleLight and JGProgressHUDStyleDark.
How can I create a HUD with clear background color?

**Comment by hemang-azilen** [comment]
@expkzb , I am looking for the exact thing for my app too. Have you ever find any workaround for this? Also, are you able to clear the background color of HUD?

**Comment by hemang-azilen** [comment]
![screen shot 2016-04-05 at 7 08 35 pm](https://cloud.githubusercontent.com/assets/16533664/14283744/2cfd13f0-fb62-11e5-9bd4-f7b1ce9ece41.png)

Please check attachment.

**Comment by JonasGessner** [comment]
See #18

**Comment by hemang-azilen** [comment]
@JonasGessner , why you're not merging that PR?

**Comment by JonasGessner** [comment]
Read the discussion on the PR.
