### ISSUE TITLE
Unsupported Architectures.

### ISSUE THREAD

**Issue by tianqiujie** [JonasGessner/JGProgressHUD#54]
ERROR ITMS-90087: "Unsupported Architectures. The executable for xxx.app/Frameworks/JGProgressHUD.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for xxx.app/Frameworks/JGProgressHUD.framework contains unsupported architectures '[x86_64, i386]'."

**Comment by JonasGessner** [comment]
That information alone doesn't really help. How are you building the framework and where are you running it?
