### ISSUE TITLE
Parallax Motion Effect Option

### ISSUE THREAD

**Issue by patrickbdev** [JonasGessner/JGProgressHUD#58]
I notice that when device is moved around, the hud moves as well, mimicing the parallax on iOS backgrounds.
I suggest allowing an option to enable/disable that named something like "enableParallaxEffect".
Additionally it may be good to provide a mode of 3 types:
- Off: Parallax always off
- Device: Parallax is based on whether user has reduce motion turn off/on http://stackoverflow.com/a/25453082/4698501
- On: Parallax always on

**Comment by JonasGessner** [comment]
I like the idea of following the global setting with `UIAccessibilityIsReduceMotionEnabled()`.

I'm not sure if the option to force enable/disable the parallax effect would really add any benefits if the hud follows the global setting?

**Comment by patrickbdev** [comment]
Some of my apps have a certain feel to them where having a parallax alert would not fit in with the rest of the UI so that's why it'd be nice to be able to override.
I think following the global setting as default would be ideal but I personally would benefit from being able to turn it off especially.
```
enum ParallaxMode {
    case Device // Follows device settings
    case Off // Always off
    case On // Always on
}

var parallaxMode = ParallaxMode.Device // .Device by default
```
