### ISSUE TITLE
how to change  height of hud view

### ISSUE THREAD

**Issue by hengchengfei** [JonasGessner/JGProgressHUD#63]
I want to change the height of view.

thank you .
<img width="286" alt="screen shot 2016-08-02 at 3 51 56 pm" src="https://cloud.githubusercontent.com/assets/3182964/17321063/3b5d6af2-58c9-11e6-8a5f-149455240180.png">

**Comment by JonasGessner** [comment]
The height of the view is determined by the contents and cannot be changed. You can however either set the `square` property to true, which which always keep the height and width equal.
