### ISSUE TITLE
iOS 10: UIView setEffect crash

### ISSUE THREAD

**Issue by kevinnguy** [JonasGessner/JGProgressHUD#64]
I'm experiencing a crash in `1.4` on a iOS 10 device that says:
```
-[UIView setEffect:]: unrecognized selector sent to instance
```
I don't see anywhere in the source where `setEffect` is being used. Any clue?

**Comment by kevinnguy** [comment]
Although reverting back to version `1.3.1` works for me

**Comment by JonasGessner** [comment]
The debugger should show exactly which line causes the crash (make sure to set an exception breakpoint). I'd need that info and please also post your code where you set up and show the HUD.

**Comment by kevinnguy** [comment]
Ahh thanks for reminding me about that! Just installed Xcode 8 so my settings are all off.

**Comment by kevinnguy** [comment]
Apologies, the bug was from my own personal code. Thanks for the quick response @JonasGessner !

**Comment by kevinnguy** [comment]
I was calling:
`((UIVisualEffectView *)self.HUDView).effect = nil;`
and I think this was crashing in `1.3.6` and above because of the `actualHUDView` implementation.
