### ISSUE TITLE
swift3 support?

### ISSUE THREAD

**Issue by georgetso** [JonasGessner/JGProgressHUD#65]

**Comment by neogame49** [comment]
+1

**Comment by patrickbdev** [comment]
Because it's an objective c codebase I imagine the source doesn't need to be changed?

**Comment by JonasGessner** [comment]
Does the framework not work with swift 3 projects?

**Comment by dougamos** [comment]
It work's for me in Swift 3.

I had to add the following to my podfile:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

I can remember if this was needed for this JGProgressHUD or other dependencies
