### ISSUE TITLE
Modal support?

### ISSUE THREAD

**Issue by dbarros** [JonasGessner/JGProgressHUD#69]
Is it possible to show a HUD but also stop the user from interacting with other controls on the screen until it is dismissed?

**Comment by JonasGessner** [comment]
That's actually the default behaviour. Please look at the docs/headers/example project before asking such a question! This is the property: https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L135
