### ISSUE TITLE
Considering text for JGProgressHUD is too long, how can I set the text in multiple lines instead  of one currently?

### ISSUE THREAD

**Issue by SenorSamuel** [JonasGessner/JGProgressHUD#70]
like if I want to show text :  "today is a wonderful day,right? "   
It now shows in a line
what if I want it shows in multiple lines so the JGProgressHUD WON'T be too large

**Comment by JonasGessner** [comment]
Setting `textLabel.numberOfLines = 0` should allow an unlimited number of lines.

**Comment by JonasGessner** [comment]
Fixed in a2f0161fa993bbd9a7de14fe8fc76dc6bb22a05a.
