### ISSUE TITLE
Please release a new version for Carthage to solve the "Codesign Resource error"

### ISSUE THREAD

**Issue by Tynox** [JonasGessner/JGProgressHUD#71]
After XCode 8.1 released, JGProgressHUD has a "Codesign Resource error" when I use Carthage to build it. 
I notice that a pull request which fixed it has been merged to the master. But there is no new release for Carthage to fix it.
Please release a new version for Carthage to fix it. Thanks.

**Comment by JonasGessner** [comment]
Done. I don't have Carthage so I haven't tested it yet, please close the issue if it works!

**Comment by Tynox** [comment]
@JonasGessner   It works! Thanks!
