### ISSUE TITLE
How to use this in swift? Any example code please?

### ISSUE THREAD

**Issue by SnitramDev** [JonasGessner/JGProgressHUD#72]
When using the sample code I get these errors on a swift project:
![screen shot 2017-01-25 at 16 16 16](https://cloud.githubusercontent.com/assets/8367143/22301183/a4d52c38-e319-11e6-8f25-a1242cb4feac.png)

**Comment by kkubkko** [comment]
Hi,

in your picture, that's Obj-C syntax, you should use it like this: 
`let myProgressHUD = JGProgressHUD(style: .dark)!
        myProgressHUD.textLabel.text = ""
        myProgressHUD.indicatorView = JGProgressHUDErrorIndicatorView()
        myProgressHUD.show(in: self.view)
        myProgressHUD.dismiss(afterDelay: 2.0)
`

Hope this helps :)
