### ISSUE TITLE
Prompt view will become larger for the second time

### ISSUE THREAD

**Issue by Musk66** [JonasGessner/JGProgressHUD#74]
When the destruction of a prompt view, once again show a prompt view, suggesting that the view width and height becomes larger

**Comment by MrLeopard** [comment]
I found that the width of the view will be with the length of the text changes, why not automatically wrap

**Comment by MrLeopard** [comment]
OK.

**Comment by MrLeopard** [comment]
OK.
I used the "\ n" line break in the text to solve the newline problem because the width of the height was calculated, with only the maximum width, no fixed width. Thanks.

**Comment by JonasGessner** [comment]
Fixed in a2f0161fa993bbd9a7de14fe8fc76dc6bb22a05a.
