### ISSUE TITLE
Wrong textLabel's frame size in case of use attributedText

### ISSUE THREAD

**Issue by landsv** [JonasGessner/JGProgressHUD#76]
The textLabel's frame size is wrong when I use `attributedText` instead of `text`, I believe there should be handled case with using `attributedText`.

I created a pull request with fix #77

**Comment by Landan** [comment]
#77

**Comment by JonasGessner** [comment]
Fixed in a2f0161fa993bbd9a7de14fe8fc76dc6bb22a05a.
