### ISSUE TITLE
make view unresponsive while hud visible

### ISSUE THREAD

**Issue by iPhoNewsRO** [JonasGessner/JGProgressHUD#80]
hello, i would like to prevent users from interacting with the app while the hud is visible. how can i achieve this?

**Comment by JonasGessner** [comment]
That's the default behaviour. See the `interactionType` property: https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L105
