### ISSUE TITLE
Errors Validating and Uploading to Appstore

### ISSUE THREAD

**Issue by rcfrias** [JonasGessner/JGProgressHUD#81]
By upgrading to Swift 3 and XCode 9, the library causes this error while uploading or validating with the app store:

Unexpected CFBundleExecutable Key. The bundle at 'Payload/Europiel.app/Frameworks/JGProgressHUD.framework/JGProgressHUD Resources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

* After removing the CFBundleExecutable Key and using CFBundlePackageType of BNDL, the new error is:

invalid Bundle Structure - The binary file 'Europiel.app/Frameworks/JGProgressHUD.framework/JGProgressHUD' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure.

** Any workaround to this?

**Comment by JonasGessner** [comment]
Are you using release version 2.0? Because 2.0 no longer contains `JGProgressHUD Resources.bundle`.

**Comment by rcfrias** [comment]
I was using an old version of JGProgressHUD, now testing with the newest one. I'll let you know about the outcome. Thnkx

**Comment by rcfrias** [comment]
Ok, using the newest version, and adding it manually as a framework seems to have fixed the problem. Thank you for your insight.
