### ISSUE TITLE
HUD not showing up when called from Facebook's `loginButtonDidCompleteLogin`

### ISSUE THREAD

**Issue by ryana** [JonasGessner/JGProgressHUD#82]
Hey guys,

I'm not sure if this is a bug in JGProgressHUD, but can anyone give me any thoughts as to why this doesn't work:

```
    func loginButtonDidCompleteLogin(_ loginButton: LoginButton, result: LoginResult) {
        switch result {
        case .failed(_):
            break
        case .cancelled:
            break
        case .success(_, _, _):
            let hud = JGProgressHUD(style: .dark)
            hud.textLabel.text = "Loading"
            hud.show(in: self.view)
            
            DispatchQueue.main.asyncAfter(deadline: .now() + 4.0) {
                hud.dismiss()
                self.performSegue(withIdentifier: "loggedInSegue", sender: self)
            }
        
            break
        }
    }
```

If I call `hud.show(in: self.view)` from `viewDidLoad` it works fine, but in this callback it does not work. It doesn't throw an error. The segue is performed as expected, but no HUD.

I've verified that in both cases, `self.view` is the same object (i.e. `Optional(<UIView: 0x7ffd3450fe40; frame = (0 0; 414 736); autoresize = W+H; layer = <CALayer: 0x60000003ce20>>)
`)

Thanks in advance!

**Comment by JonasGessner** [comment]
You're probably running this on a background thread.
