### ISSUE TITLE
Bug at JGProgressHUDRingIndicatorLayer code 

### ISSUE THREAD

**Issue by semix2** [JonasGessner/JGProgressHUD#84]
In JGProgressHUDRingIndicatorLayer.drawInContext(), center is not correct.

CGPoint center = CGPointMake(rect.origin.x + (CGFloat)floor(rect.size.height/2.0f), rect.origin.y + (CGFloat)floor(rect.size.height/2.0f));

This code should be changed to

CGPoint center = CGPointMake(rect.origin.x + (CGFloat)floor(rect.size.width/2.0f), rect.origin.y + (CGFloat)floor(rect.size.height/2.0f));

**Comment by JonasGessner** [comment]
Please open a pull request where this is fixed in all relevant places.
