### ISSUE TITLE
Issue with indicator appearing at topLeft instead of center

### ISSUE THREAD

**Issue by aashishSapkotaKC** [JonasGessner/JGProgressHUD#85]
The indicator appears at the top left of the progress hud view. It used to appear at center. I just upgraded my project from Swift 2 to Swift 4, in Xcode 9.

**Comment by JonasGessner** [comment]
Please show me the code where you are seeing this issue, otherwise I won't be able to reproduce the issue easily.

**Comment by abdbinrus93** [comment]
if ((DataManager.sharedInstance.loggedInUser?.id) != nil) {
            
            DataManager.sharedInstance.signedIn = false
            DataManager.sharedInstance.loggedInUser = nil
            
            self.hud.indicatorView = JGProgressHUDSuccessIndicatorView()
            self.hud.textLabel.text = "Signed out"
            self.hud.show(in: self.view, animated: true)
            self.hud.dismiss(afterDelay: 3, animated: true)
            
            let when = DispatchTime.now() + 2
            DispatchQueue.main.asyncAfter(deadline: when) {
                
                let homeViewController = HomeViewController()
                self.sideMenuController?.hideRightViewAnimated()
                self.homeNavigationController.pushViewController(homeViewController, animated: true)
            }

**Comment by abdbinrus93** [comment]
![screen shot 2018-01-25 at 10 52 13 am](https://user-images.githubusercontent.com/32546036/35372858-d5a46f18-01bd-11e8-85ef-0471eaa1f2ba.png)

**Comment by aashishSapkotaKC** [comment]
Yeah, it used to work perfectly fine, before in Swift 2. After migrating the project to swift 4, it behaviour has changed. Need to change the working library now!! :( 👎

**Comment by abdbinrus93** [comment]
What should I do now ?

**Comment by StarWars** [comment]
@JonasGessner I experience the same issue. It takes a few seconds before the indicator gets centered. Seems like the JGProgressHUD's layout gets invalidated too late.

**Comment by JonasGessner** [comment]
@abdbinrus93 's example code is incomplete. If anyone else could post an example which includes creation, setup and displaying of the hud that would be helpful. Please also note that the nature of open source collaborations is not to ask the creator to fix a bug but to take initiative to fix something yourself and then post a pull request with the bug fix.

**Comment by bigearsenal** [comment]
The problem appears when we reuse the indicatorView or simply set a new indicator View
`
hud.indicatorView = JGProgressHUDSuccessIndicatorView()
hud.textLabel.text = "This is a very long long long long long text!"
hud.show(in: view)
`
And then, show the same hud
`
hud.indicatorView = JGProgressHUDIndeterminateIndicatorView()
hud.textLabel.text = "Indeterminate..."
hud.show(in: view)
`
Even when I dismiss the hud every time I wanna change IndicatorView, it won't help
