### ISSUE TITLE
HUD cuts off text

### ISSUE THREAD

**Issue by DaneMcGowan** [JonasGessner/JGProgressHUD#91]
I am sure there is a way to fix this that I am just not seeing in the docs. Often when running on my phone, the HUDs appear too small and error/progress/etc messages like "LongTextString" are displayed as "LongTe...".

I tried to setting `square` to true on all the HUDs, since this seemed to fix it once. However, it isn't a reliable fix. If I rotate my phone, the HUD gets bigger in landscape mode and the full message is displayed, and then when I rotate back to portrait the full message is still displayed. Any idea how I can make sure it's fully displayed all the time?

**Comment by JonasGessner** [comment]
Could you please post your code so I can try and reproduce it?

**Comment by JonasGessner** [comment]
Last bump
