### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by mudassirzulfiqar** [JonasGessner/JGProgressHUD#93]
Hi I have imported the library using POD like I do with all libraries.
It can be see in pod frameworks directory but when I import this in any file it says NO MODULE FOUND..

**Comment by JonasGessner** [comment]
Could you post your podfile? It works fine for me and have not had any other reports on this issue and lots of people use this on CocoaPods.

**Comment by rehannali** [comment]
I've having same problem and i think framework is not found my xcode for JGProgressHUD.
This issue caused if you use static libraries because i think this module currently isn't support static libraries.
`use_frameworks!` 
uncomment this line to use this.

**Comment by rehannali** [comment]
@JonasGessner Could you please make it static?

**Comment by JonasGessner** [comment]
I would recommend using frameworks (`use_frameworks!`). If you're not using frameworks you necessarily have to use the bridging header in Swift projects since this library is written in Objective-C.
