### ISSUE TITLE
JGProgressHUB appearing on the top of the screen when UItableViewController is used

### ISSUE THREAD

**Issue by gustavoserra** [JonasGessner/JGProgressHUD#94]

**Comment by JonasGessner** [comment]
https://upthemes.com/blog/2014/02/writing-useful-github-issues/

**Comment by JonasGessner** [comment]
@gustavoserra There's literally no useful information in this issue. How do you think I can fix a bug from one sentence full of typos?

**Comment by gustavoserra** [comment]
I'm using UITableViewController and I've already tried to show the HUB in the `self.view` and on the `self.tableView` but it appears on the top of the screen.

```
let hud = JGProgressHUD(style: .dark)
hud.textLabel.text = "Carregando produtos"
hud.interactionType = .blockAllTouches
hud.show(in: self.tableView)
```

![img_bf84a7a794e2-1](https://user-images.githubusercontent.com/29704729/42134564-68905958-7d3e-11e8-8bd1-278ff1760891.jpeg)

**Comment by JonasGessner** [comment]
The bounds of the UITableView change when you scroll, hence the HUD moves too. Show the HUD in the [navigation controller's view](https://github.com/JonasGessner/JGProgressHUD/blob/master/Examples/JGProgressHUD-Tests/JGMainViewController.m#L109) instead.
