### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by farzin680** [JonasGessner/JGProgressHUD#96]
Hi ,
I Searched a lot In This Library and Couldn't Find Any Font Adjustment Or Property To Set a New One.

Is It In Your Plans To Add Something Like That ?

**Comment by JonasGessner** [comment]
You can simply change the `font` property of `textLabel` and `detailTextLabel`: https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L69

**Comment by farzin680** [comment]
Thank You , I Really Missed It
