### ISSUE TITLE
How to change the color of indicatorView?

### ISSUE THREAD

**Issue by Y2JChamp** [JonasGessner/JGProgressHUD#97]
I'm trying this code but this doesn't work:
```
hud.indicatorView?.tintColor = UIColor.myColor()
hud.textLabel.text = NSLocalizedString("Loading", comment: "").uppercased()
hud.textLabel.textColor = UIColor.myColor()
hud.textLabel.numberOfLines = 2
hud.show(in: view)
```

**Comment by JonasGessner** [comment]
Use -setColor to change the color of the default indicator view (JGProgressHUDIndeterminateIndicatorView).

**Comment by maxmika** [comment]
Hi @JonasGessner , could you help me out please?
I'm using an indeterminate activity indicator and I'd like to change the indicator to another color in Swift. I tried a few things (like below), and in the view debugger I could see the indicatorView's tintColor property **did** change to my color, but nevertheless the indicator was still in its default gray color.

What do I have to write to achieve this?
Danke im Voraus 🙏🏻
`

        let hud = JGProgressHUD(style: .extraLight)
        
        hud.indicatorView?.tintColor = .porscheRed
        hud.indicatorView?.tintColorDidChange()
        
        if let v = hud.indicatorView as? JGProgressHUDIndeterminateIndicatorView {
            v.setColor(.porscheRed)
        }
`
