### ISSUE TITLE
change PIE indicator color

### ISSUE THREAD

**Issue by corsairdoo** [JonasGessner/JGProgressHUD#99]
```
// method 1 - Not Working
hud.indicatorView = JGProgressHUDPieIndicatorView()
hud.indicatorView?.tintColor = UIColor.red // indicatorView doesn't have [color] [fillColor]

// method 2 - Not Working
let indicator = JGProgressHUDPieIndicatorView()
indicator.color = UIColor.red
hud.indicatorView = indicator

// method 3 - Working
let indicator = JGProgressHUDPieIndicatorView()
hud.indicatorView = indicator
indicator.color = UIColor.red
```

If it's not a bug, I think you should explain how to change color of Pie-Indicator.

**Comment by Nododo** [comment]
> ```
> // method 1 - Not Working
> hud.indicatorView = JGProgressHUDPieIndicatorView()
> hud.indicatorView?.tintColor = UIColor.red // indicatorView doesn't have [color] [fillColor]
> 
> // method 2 - Not Working
> let indicator = JGProgressHUDPieIndicatorView()
> indicator.color = UIColor.red
> hud.indicatorView = indicator
> 
> // method 3 - Working
> let indicator = JGProgressHUDPieIndicatorView()
> hud.indicatorView = indicator
> indicator.color = UIColor.red
> ```
> 
> If it's not a bug, I think you should explain how to change color of Pie-Indicator.

...so crazy
